# Generated by Django 4.0.3 on 2022-03-17 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='slug',
        ),
    ]
