# Generated by Django 4.0.3 on 2022-03-21 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_noticia_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('Política', 'Economia'), ('Social', 'Esports'), ('Opinió', 'Successos')], default='Sense categoria', max_length=20),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='cos',
            field=models.CharField(default='DEFAULT VALUE', max_length=9999999),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='subtitol',
            field=models.CharField(default='DEFAULT VALUE', max_length=400),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titol',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
        migrations.AlterField(
            model_name='valoracio',
            name='lector',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='news.lector'),
        ),
        migrations.AlterField(
            model_name='valoracio',
            name='noticia',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='news.noticia'),
        ),
    ]
