# Generated by Django 4.0.3 on 2022-03-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_periodista_name_periodista_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lector',
            name='phone_number',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
    ]
