# Generated by Django 4.0.3 on 2022-03-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_lector_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(default='DEFAULT VALUE', max_length=20)),
                ('subtitol', models.CharField(default='DEFAULT VALUE', max_length=120)),
                ('cos', models.CharField(default='DEFAULT VALUE', max_length=99999)),
            ],
        ),
    ]
