# Generated by Django 4.0.3 on 2022-03-22 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='lector',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 0, 43, 27, 628031)),
        ),
        migrations.AddField(
            model_name='periodista',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 0, 43, 27, 628031)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 0, 43, 27, 627030)),
        ),
    ]
