# Generated by Django 4.0.3 on 2022-03-22 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_lector_last_login_periodista_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lector',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 0, 44, 28, 725904)),
        ),
        migrations.AlterField(
            model_name='periodista',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 0, 44, 28, 725904)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 0, 44, 28, 724903)),
        ),
    ]
