# Generated by Django 4.0.3 on 2022-03-22 23:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_lector_last_login_alter_periodista_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lector',
            name='last_login',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 22, 23, 50, 33, 920065, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='periodista',
            name='last_login',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 3, 22, 23, 50, 33, 920065, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 22, 23, 50, 33, 920065, tzinfo=utc)),
        ),
    ]
