# Generated by Django 4.0.3 on 2022-03-22 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_alter_lector_last_login_alter_periodista_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lector',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 0, 55, 16, 431162)),
        ),
        migrations.AlterField(
            model_name='periodista',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 0, 55, 16, 431162)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 0, 55, 16, 430162)),
        ),
    ]
