# Generated by Django 4.0.3 on 2022-03-22 23:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_remove_lector_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lector',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 22, 23, 58, 22, 112882, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='periodista',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 22, 23, 58, 22, 112882, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
